name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose up --exit-code-from autotests || true                                                                                  

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history  # Создает директорию для истории Allure

      - name: Copy history from gh-pages to allure-results (if exists)
        run: |
          if [ -d "./.github/gh-pages/history" ] && [ "$(ls -A ./.github/gh-pages/history)" ]; then
            echo "Copying existing history..."
            sudo cp -R ./.github/gh-pages/history/* allure-results/history/
          else
            echo "No history found, skipping copy"
          fi

      - name: Generate Allure report
        run: |
          docker compose run autotests /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          sudo mkdir -p ./.github/gh-pages/history  # Создаем директорию если не существует
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true